### ISSUE TITLE
choices focus issue.

### ISSUE THREAD

**Issue by peacetara** [peacetara/slab#1]
osascript(applescript) doesn't take focus. Need a better way to ask for choices from user, or a way to get applescript to take focus.

**Comment by jabofh** [comment]
Please test whether my update fixes this for you...

**Comment by peacetara** [comment]
It does, but then iTerm2 wouldn't get focus back when osascript left.  I've fixed that with my latest push. WOO! Thanks, who would have thought "System Events" == osascript 💯
