### ISSUE TITLE
Entries in "Trash" gets matched

### ISSUE THREAD

**Issue by jabofh** [peacetara/slab#5]
Currently entries in "Trash" (i.e. deleted but not cleared) gets matched by `slab`. Those entries should get ignored...

**Comment by peacetara** [comment]
Oh I didn't realize that. in the  items table there is:  ```trashed INTEGER NOT NULL```,
so in the ```_loadItems()``` function the query should probably be something like:
```select distinct i.id, c.singular_name as category, i.overview_data from items i, categories c where c.id = i.category_id and i.trashed is 0 order by i.id```
or something, whatever a non-trashed entry is.  I don't have a trashed entry to test. We should probably put a trashed entry in the ./OnePassword.sqlite file that can be used for testing.

**Comment by jabofh** [comment]
It seems like `and not i.trashed` did the trick...
